drone_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, url_for, flash, redirect
from drone_inventory.forms import UserLoginForm
from drone_inventory.models import User, db, check_password_hash
from flask_login import login_user, login_required, logout_user

auth = Blueprint('auth', __name__, template_folder='auth_templates')


@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        #print(email, password)
        
        # create (instantiate) a new user class and add that user into the table
        new_user = User(email, password)
        db.session.add(new_user)
        db.session.commit()
        # Flash message for registration success
        flash(f'You have successfully registered an account under {email}', 'user-created')
        # Redirect to home page after signing up
        return redirect(url_for('site.home'))

    return render_template('signup.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)

        #Attempting to find this person in the db based on email
        logged_user = User.query.filter(User.email == email).first()
        if logged_user and check_password_hash(logged_user.password, password):
            login_user(logged_user)
            flash('You were successfully logged in.', 'auth-success')
            # Redirecting upon successful sign in
            return redirect(url_for('site.home'))

        else:
            flash('Your Email/Password is incorrect', 'auth-failed')
            return redirect(url_for('auth.signin'))


    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have succesffuly logged out.', 'auth-success')
    return redirect(url_for('site.home'))

drone_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required


site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

drone_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.js"></script>
<title>Operators Drone Inventory</title>
</head>
<body>
    <!-- Navbar goes here -->
    <nav class="ct-nav">
        <div>
            <img src="../static/images/Coding Drones Logo.png" alt="">
        </div>
         <!-- Nav items begin here -->
         <div>
             <ul id="horizontal-list">
                 <a href="{{ url_for('site.home') }}">
                     <li>The Coding Drones Project</li>
                 </a>
                 <a href="">
                     <li>Donate</li>
                 </a>
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('site.profile') }}">
                        <li>Profile</li>
                    </a>
                    <a href="{{ url_for('auth.logout') }}">
                        <li>Log Out</li>
                    </a>
                {% else %}
                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Sign Up Free</li>
                    </a>
                {% endif %}
             </ul>
         </div>
    </nav>
    <!-- End of Nav -->
    {% block content %}
    {% endblock content %}

   





</body>
</html>